compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  projektionisten:
    npmAlwaysAuth: true
    npmAuthIdent: "projektionisten:PsDriver2019"
    npmPublishRegistry: "https://verdaccio.projektionisten.de/"
    npmRegistryServer: "https://verdaccio.projektionisten.de/"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
