nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.5.1.cjs

npmScopes:
  projektionisten:
    npmAlwaysAuth: true
    npmAuthIdent: "projektionisten:PsDriver2019"
    npmPublishRegistry: "https://verdaccio.projektionisten.de/"
    npmRegistryServer: "https://verdaccio.projektionisten.de/"
